### ISSUE TITLE
Quests cannot be completed lately: "The quest has ended due to an unknown error."

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#101]
I find that a number of different quests cannot be completed as of late, both ones that I have and haven't done before in the past. A message pops up preventing the completion of quests: `The quest has ended due to an unknown error.`  Could it be due to redeploying the server with the most recent update changes?

Here are some examples:
- I Need to Find My Daughter 1
- Maya of Henesys*
- Looking for the Red Cape*
- Searching for Fossils

*The ones that are marked were completed before.

**Comment by Araraura** [comment]
I've had the same issue with "Mr. Wetbottom's Secret Book" 2nd stage (Where you progress the quest by first talking to Ronnie)

**Comment by sewil** [comment]
Fixed in 319c4c7aeb0c69a0a8c293cdaed981d270fc5355 and 3b04e469e159315d3cc83df3e4814ffc7fc54379

**Comment by Araraura** [comment]
> I've had the same issue with:
> 
>     * "Mr. Wetbottom's Secret Book" 2nd stage (Where you progress the quest by first talking to Ronnie)
> 
>     * "A Delivery to a Lost Time" (When you give the Pendulum to Grandpa Clock)
> 
>     * "To the New World" (When accepting the quest from Kriel)

Fixed
