### ISSUE TITLE
Quest completion not saved

### ISSUE THREAD

**Issue by Araraura** [sewil/OpenMG#102]
I've had an issue with the quest "Building a New House For Blackbull" where after completing the quest and then relaunching the game, the quest will be available again like it was never completed.

I'll update this issue if I find more quests with the same problem

**Comment by sewil** [comment]
Should be fixed in 319c4c7aeb0c69a0a8c293cdaed981d270fc5355, please re-test

**Comment by Araraura** [comment]
Fixed
