### ISSUE TITLE
The number 32,767 appears to be the upper limit for stats

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#109]
This number 32,767 appears to be the upper limit you can have for HP, MP, STR, DEX, INT, LUK, and Fame from what I understand so far. Whether or not it's an issue is what we make of it,

For instance, if you have max HP/MP at 30,000, Hyper Body will boost it up to 48,000, but you can only really get 32767/48000 once fully healed.

**Comment by Araraura** [comment]
I don't think HP/MP are supposed to go beyond 30k, even with Hyper Body applied. Fame is also ([supposed to be](https://github.com/sewil/OpenMG/issues/108)) capped at 30k, and there is no way to legitimately reach such high STR/DEX/INT/LUK in early versions like this.

**Comment by sewil** [comment]
This is the upper limit since it's the max value for a signed short (16-bit integer) that the client and server uses for stat values among other things.
