### ISSUE TITLE
Time interval in which HP is deducted in certain areas is incorrect

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#110]
The time interval in which HP is deducted in areas like El Nath or Aqua Road is incorrectly set to 10s, which is the exact amount of time it takes for players to recover HP when standing still. This would mean there's no chance that players would ever die.

According to [this](https://maplestory.fandom.com/wiki/Forest_of_Dead_Trees_III), it's -10HP/5s in El Nath. According to [this](https://maplestory.fandom.com/wiki/The_Grave_of_a_Wrecked_Ship), it's -6HP/5s in Aqua Road.

**Comment by sewil** [comment]
The MapleStory wiki describes the latest version which is inaccurate for v22. It's correct that it deducts every 10 seconds, so you can survive by standing still, but if hanging by a rope and go AFK you can die. This is how other low-version servers like MG2 and Phoenix does it.
