### ISSUE TITLE
Animation issue when using Assassin/Hermit skills with Soul Arrow buff on

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#113]
You can see the Soul Arrow projectile when using normal attacks, Lucky Seven, and Drain. If you use Avenger, the giant Shuriken will not spin across the air.

On second thought, maybe we can treat this bug as a feature. It's actually kind of cool. Just fix the non-spinning Avengers and we're good. :)

**Comment by sewil** [comment]
This is a client-side "bug", and there's no reason why a hermit should have the Soul Arrow buff for bows anyway (This isn't a rb server lol). The only reason it works as it does now is because it counts both throwing stars and arrows as "bullets".
