### ISSUE TITLE
MP Eater activates when using some attack skills outside of Magicians if /maxskills was used

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#117]
The command `/maxskills` is handy in the sense that it quickly assigns SP to all skills; however, it applies SP to all job skills. It appears that this one example fell through where passive skills unrelated to a non-GM job you assigned yourself might still be inherited from the other jobs when that should only be applicable to GMs.

So far, these are the skills that seem to trigger MP Eater:
- Bandit / Chief Bandit Skills
- Power Knock-Back

**Comment by sewil** [comment]
This makes sense, but this is not a rb server so there'd be no scenario where a bandit would have mp eater anyway so it's a non-issue.
