### ISSUE TITLE
Having both /goto and /map is redundant?

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#118]
Both commands will work if you type in a map ID. However, `/goto` is more useful because you can type the shorthand of towns without having to look up the map ID. However, `/map` currently only works with map IDs. If you were to type in a town, it will always teleport you to **Maple Road: West Entrance to Mushroom Town**. Even if we do fix `/map` to accept strings, that's essentially `/goto` but with a different name.

**Comment by Araraura** [comment]
I don't think either should be removed. `/goto` is essentially a shortcut for `/map`. I found myself using both.
Especially when there are specific maps I wanna reach, I would use `/map` to teleport there directly, instead of using `/goto` to the nearby town and walking to the map I want by foot.

**Comment by Araraura** [comment]
> What I'm saying is `/goto` works by typing the shorthand for towns AND specific map IDs, while `/map` only works with map IDs. This would make `/map` a redundant and less useful command than `/goto`, which can't do both.

Ah, didn't realize it can also take map IDs.

**Comment by sewil** [comment]
/m, /map, and /goto all lead to the same command. You can use map ids or the string for certain towns with all these commands.
