### ISSUE TITLE
Items (Equip/Use/Etc/Set-up/Cash) with incorrect stats

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#27]
Thief Overall Katinas' (Blue, Dark, Red) have the incorrect requirements and stats. Green is the only exception that is correct out of the 4 colored variants.

**Comment by sewil** [comment]
There's two frozen tuna actually, one level 10 for all jobs and the level 20 is for beginners only (although it says all jobs, which i think is a client bug)

**Comment by sewil** [comment]
79cd835d6ccccc6b6d4d59b34df90e319ec817ea
5b63cb114c30d8f6eeb7f2a6e1e48c676b822dd9
d9284bf2a1d29155478698ae2934f02811ebd858
