### ISSUE TITLE
Summoned Monster ID: 8510000 Pianus and crashed

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#28]
Game crashed after using "/spawn 8510000" on the left side of the first map on Maple Island. I can get past the channel select screen, but once the character appears in the map, it crashes before it can even land on the ground. Probably not a channel crash, but a map crash that traps all those who are in the map, or even enters that map.

**Comment by sewil** [comment]
Data.wz related, need to update the client wz

**Comment by sewil** [comment]
Fixed with Data.wz update
