### ISSUE TITLE
Permanent Ban due to damage calculation being inaccurate?

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#33]
- Character is a Lv. 8 Magician with base stats (4, 4, 48, 4).
- Stats after wearing equips: STR 25, DEX 19, INT 48, LUK 4
ATTACK 14~61, ACCURACY 17, HANDS 71
- Given a Sword (+7) perfectly scrolled:+21 STR and 52 W.ATT.
- Wearing Leather Sandals (+5) perfectly scrolled: +15 DEX.

Here's what the notice says:
> Enqueued delayed permban for userid "", charname "", level 8, reason (Hack) Melee damage hack (low level), hit 57 (max: 53), map "" in 5 seconds...

**Comment by sewil** [comment]
This looks like some old code that should've been replaced by the CalcTargetDamage class, it was unused in debug mode which is why I didn't see it until now...
