### ISSUE TITLE
Maple Weapons named incorrectly

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#34]
Incorrect -> Correct
- Maple Celtic Sword -> Maple Soul Singer
- Maple Two-Handed Axe -> Maple Dragon Axe
- Maple Big Maul -> Maple Doom Singer
- Maple Spear -> Maple Impaler
- Maple Pole Arm -> Maple Scorpio
- Maple Hunters -> Maple Soul Searcher
- Maple Thrones -> Maple Claw

GMS did not use these names. Unsure if they came from different regions. It would be a good idea to double-check the names of other items to ensure consistency.

**Comment by sewil** [comment]
Pretty sure these are the OG names, so it depends where your nostalgia lies, but I agree with changing them.

**Comment by sewil** [comment]
Fixed with new Data.wz. Pretty sure these were the names used in v8 and I just never got around to updating them.
