### ISSUE TITLE
Quest items can be obtained from monsters/reactors before the quest has been started

### ISSUE THREAD

**Issue by LuneArk** [sewil/OpenMG#39]
Quest items that come from monster drops or reactors seem to be invisible if the quest hasn't been started. They are clearly there, but cannot be seen or looted. However, if you exit and return to the same map, you can see them, and even pick them up. Once picked up, the items will remain floating as "ghost items"; you cannot pick them up multiple times. They will disappear once exiting and returning to the same map.

**Comment by sewil** [comment]
Which mob/map was this tested on? Which quest item? Just tried on wild boars and couldn't reproduce this issue. Were you in a party with anyone who had the quest at the time?

**Comment by sewil** [comment]
a62209c48cbfd7aed92602e5d619f3d537faaa51
