### ISSUE TITLE
Handing quests don't always take items from inventory

### ISSUE THREAD

**Issue by Araraura** [sewil/OpenMG#97]
Seems like handing over certain quests don't always take away the required items to complete them from your inventory. So far I noticed it with John's Pink Flower Basket and Just Another Day at Work

**Comment by sewil** [comment]
Fixed John's Flower Basket. For Just Another Day At Work, the camera is removed when you have taken photos of all the Roly-Polys and complete the quest-chain. (Quest 3220)

**Comment by Araraura** [comment]
> Fixed John's Flower Basket ([a1a7d34](https://github.com/sewil/OpenMG/commit/a1a7d34b3007af6fddbedfdd2ec809d2bda9b8ed)). For Just Another Day At Work, the camera is removed when you have taken photos of all the Roly-Polys and completed the quest-chain. (Quest 3220)

Seems to also be an issue with John's Present https://github.com/sewil/OpenMG/blob/master/DataSvr/NxExports/ClientData.nx/Quest/Act.img.xml#L1723
Also looking at the inventory after completing the chainquest, I was left with 10 cameras and Photo of Roly-Poly 10
![image](https://github.com/user-attachments/assets/7c9b95c2-5542-45c1-850c-b83cb8f696e5)
